<a href="https://colab.research.google.com/github/M-Waweru/ML_Unit/blob/master/MLLab_SVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Example of SVD

In [0]:
import numpy as np
from numpy.linalg import svd

In [0]:
A = np.array([[1,2,3],[2,3,4]])
A

array([[1, 2, 3],
       [2, 3, 4]])

In [0]:
U, S, Vt = svd(A)

In [0]:
print(U)

[[-0.56959484 -0.82192562]
 [-0.82192562  0.56959484]]


In [0]:
# Print singular values of A
print(S)

print(np.diag(S))

[6.54675564 0.37415323]
[[6.54675564 0.        ]
 [0.         0.37415323]]


In [0]:
print(Vt)

[[-0.33809817 -0.55064932 -0.76320047]
 [ 0.84795222  0.17354729 -0.50085764]
 [ 0.40824829 -0.81649658  0.40824829]]


# Truncated SVD

In [0]:
from sklearn.decomposition import TruncatedSVD
import pandas as pd

In [0]:
from google.colab import files 
uploaded = files.upload()

Saving Nairobi Office Price Ex.csv to Nairobi Office Price Ex.csv


In [0]:
data = pd.read_csv('Nairobi Office Price Ex.csv')

In [0]:
nominal = ['LOC', 'FUR', 'WATER', 'HK_SER']
ordinal = ['AMB', 'PROX_SCH', 'PROX_ROAD', 'PROX_MALL']
numerical = ['SIZE']
target = ['PRICE']
categorical_data = data.select_dtypes(include=['object']).copy()
column_names = list(categorical_data.columns)

for feature in column_names:
  categorical_data[feature] = categorical_data[feature].astype('category')

for feature in ordinal:
  categorical_data[feature] = categorical_data[feature].cat.codes

In [0]:
categorical_data.head()

LOC  FUR  AMB  PROX_SCH  PROX_ROAD  PROX_MALL WATER HK_SER
0     karen  yes    2         0          1          1   yes    yes
1  madaraka  yes    1         1          1          1    no     no
2     karen   no    0         0          1          1   yes    yes
3     karen  yes    1         0          0          0   yes    yes
4  buruburu   no    1         0          1          1   yes    yes

In [0]:
data_copy = categorical_data.copy()
data_copy = pd.concat([pd.get_dummies(data_copy[nominal], prefix='Estate'), data_copy], axis=1)
data_copy.drop(nominal, axis=1, inplace=True)

new_data = pd.concat([data_copy, data[numerical], data[target]], axis=1)
# new_data

In [0]:
# new_data
X = new_data.drop('PRICE', 1)
y = data[target]
data_array = X.to_numpy()
# data_array

In [0]:
Tsvd = TruncatedSVD(n_components=2)
data_approx = Tsvd.fit_transform(data_array)

In [0]:
Tsvd.singular_values_

array([190.59287448,   3.75044979])

In [0]:
data_approx
final_data 

array([[32.59067248, -0.31296456],
       [53.46778496, -0.51284032],
       [61.5425652 ,  1.84399183],
       [47.50479939,  0.43325415],
       [59.84701785,  0.98922952],
       [55.18765095, -0.66580331],
       [52.29472771, -1.58958668],
       [39.36187158, -1.08471401],
       [48.13307416, -0.2865976 ],
       [52.58778358, -1.40400383],
       [45.44308725,  1.16566524],
       [54.38965254,  0.58800498],
       [44.20133601, -0.79910776],
       [58.22132174,  0.7714815 ]])